services:
  api:                              #Nome do meu servico
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build: .                        #"faça build e isso vai ta na raiz do meu projeto"
    container_name: backend         #nome do container - customizado
    ports:                          #porta do docker run, nao vai precisar mais rodar na mao
      - "3000:3000"
    #command:  npm start
    depends_on:
      db:
        condition: service_healthy

  db:
    image:  postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s